spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/finance"
    username: dev
    password: dev129
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
        hibernate:
          generate_statistics: true
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
  task:
    scheduling:
      pool:
        size: 5

server:
  servlet:
    context-path: "/api"
  error:
    include-message: always
